spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/-------
    username: -------
    password: -------
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
#    properties:
#      hibernate.format_sql: true
logging:
  level:
    org.springframework: ERROR
    com.ratmirdudin.userservice: TRACE
