spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/test_app_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    org.springframework: ERROR
    com.ratmirdudin.userservice: TRACE
